export const Users = [
  {
    id: 1,
    profilePicture: "/assets/person/1.jpeg",
    username: "Naynyizin TheFvvker",
  },
  {
    id: 2,
    profilePicture: "/assets/person/2.jpeg",
    username: "Quill",
  },
  {
    id: 3,
    profilePicture: "/assets/person/3.jpeg",
    username: "Nova",
  },
  {
    id: 4,
    profilePicture: "/assets/person/4.jpeg",
    username: "Rikimaru",
  },
  {
    id: 5,
    profilePicture: "/assets/person/5.jpeg",
    username: "Greedy A.M",
  },
  {
    id: 6,
    profilePicture: "/assets/person/6.jpeg",
    username: "Zwe Gyi",
  },
  {
    id: 7,
    profilePicture: "/assets/person/7.jpeg",
    username: "Fucking Kid",
  },
  {
    id: 8,
    profilePicture: "/assets/person/8.jpeg",
    username: "Jennie Kim",
  },
  {
    id: 9,
    profilePicture: "/assets/person/9.jpeg",
    username: "N3zuk0",
  },
  {
    id: 10,
    profilePicture: "/assets/person/10.jpeg",
    username: "Moonpie",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Hey, this's my first post :)",
    photo: "/assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 2,
    like: 11,
    comment: 6,
  },
  {
    id: 2,
    desc: "yummy yummy !",
    photo: "./../../assets/post/2.jpeg",
    date: "2 hours ago",
    userId: 2,
    like: 2,
    comment: 3,
  },
  {
    id: 3,
    photo: "./../../assets/post/3.jpeg",
    date: "15 mins ago",
    userId: 3,
    like: 22,
    comment: 15,
  },
  {
    id: 4,
    photo: "./../../assets/post/4.jpeg",
    date: "5 hours ago",
    userId: 4,
    like: 8,
    comment: 1,
  },
  {
    id: 5,
    desc: "Gonna be fun ! ! !",
    photo: "./../../assets/post/5.jpeg",
    date: "10 hours ago",
    userId: 5,
    like: 20,
    comment: 3,
  },
  {
    id: 6,
    desc: "pussy pussy mi mi :)",
    photo: "./../../assets/post/6.jpeg",
    date: "22 hours ago",
    userId: 6,
    like: 44,
    comment: 20,
  },
  {
    id: 7,
    photo: "./../../assets/post/7.jpeg",
    date: "1 day ago",
    userId: 7,
    like: 12,
    comment: 3,
  },
  {
    id: 8,
    photo: "./../../assets/post/8.jpeg",
    date: "2 days ago",
    userId: 8,
    like: 2,
    comment: 3,
  },
  {
    id: 9,
    photo: "./../../assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 24,
    comment: 8,
  },
  {
    id: 10,
    desc: "I'm so lonely...",
    photo: "./../../assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 55,
    comment: 15,
  },
];
